
{% set name = "XRFtomo" %}
{% set version = "1.0.7" %}
{% set repo = "fabricioSMarin" %}
#tomography
#fabricioSMarin

package:
  name: {{ name|lower }} 
  version: {{ version }}

#source:
  url: https://github.com/{{ repo }}/{{ name }}/archive/v{{ version }}.tar.gz
#    path:  /Users/fabriciomarin/Downloads/xrftomo-1.0.7-py_0.tar.bz2
  # sha256: b1c7a9655e76a86ab555fb1360adcd61ae14bcd8e5397bb38c76d8750b2c84f2
  # url: https://github.com/{{ repo }}/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: 986c4ea85c7fe8bcef274b7085209b74e8a93acd444ad1f9b947fb3f1352cbbb
  extra:
    channels:
      - conda-forge

build:
  noarch: python
  number: 0
#  script: "{{ PYTHON }} -m pip install ."
  # script: "{{ python }} setup.py install"
  # entry_points: 
  #   - xrftomo = xrftomo.xrftomo:main
#  entry_points:
#    - xrftomo = xrftomo.__main__:main
  # ignore_prefix_files:
  #   - xrftomo

requirements:
  host:
    - python =3.9
    - pip
  run:
    - python =3.9
    - dxchange
    - tomopy
    - dxfile
    - h5py
    - matplotlib
    - numpy
    - pandas
    - pyqt >=5
    - pyqtgraph
    - scipy
    - seaborn
    - setuptools
    - scikit-image
    - pywin32   [win]
    - astropy

test:
  source_files:
    - ../Menu/menu_installer.py
  imports:
    - xrftomo

about:
  home: https://github.com/{{ repo }}/XRFtomo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Tomography software for APS beamlines'
  description: |
    XRFtomo brings together a variety of image processing tools used for preparing, 
    processing and reconstructing 3D renditions of samples imaged using a 
    synchrotron-based x-ray fluorescence (XRF) microprobe or nanoprobe at the 
    Advanced Photon Source (APS).
  dev_url: https://github.com/{{ repo }}/XRFtomo

extra:
  recipe-maintainers:
    - FabricioSMarin


